sudo: false
language: scala

scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12

jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "monix/monix-circe" && sbt ++$TRAVIS_SCALA_VERSION publish
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "monix/monix-circe" && test $TRAVIS_SCALA_VERSION == "2.13.1"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
